import Head from 'next/head'
import Hero from '../components/Hero'
import Bloggingpost from '../components/Bloggingpost'
import Pricing from '../components/pricing'
import Statics from '../components/Statics'
import Testimonial from '../components/Testimonial'
import Team from '../components/Team'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Blogging_Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" href="https://thumbs.dreamstime.com/b/blue-letter-b-logo-power-blue-letter-b-logo-power-logo-luxury-minimalist-badge-logo-edge-contrast-color-logo-114749609.jpg" type="image/x-icon" />
      </Head>

      {/* Hero section */}
      <Hero/>
      {/* Blogging Post */}
      <Bloggingpost/>
      {/* Pricing */}
      <Pricing/>
      {/* Statics */}
      <Statics/>
      {/* Testimonials */}
      <Testimonial/>
      {/* Our Team */}
      <Team/>

    
    </div>
  )
}
